### ISSUE TITLE
next working as step

### ISSUE THREAD

**Issue by AHaymond** [nixme/pry-debugger#47] opened 2014-03-11 17:38 UTC
I have installed pry-debugger with pry-rails. When using binding.pry, the `next` command is working as the `step` command. I am using pry version 0.9.12.6 and pry-debugger 0.2.2

**Comment by nixme** [comment] 2014-03-11 18:11
Dupe of #34. Please use `pry-byebug` for now.

**Closed as completed by nixme** 2014-03-11 18:11 UTC

**Comment by AHaymond** [comment] 2014-03-11 18:33
I just discovered pry-byebug as a workaround. Thanks for the tip anyhow.
