### ISSUE TITLE
next and step seems to works as same

### ISSUE THREAD

**Issue by GCorbel** [nixme/pry-debugger#40] opened 2013-08-20 21:05 UTC
Hello,

When I'm using pry-debugger, in a rails application, I have this : 

```
    9: def new
   10:   painting.address = current_user.address
   11:   painting.postal_code = current_user.postal_code
   12:   binding.pry
=> 13:   painting.city = current_user.city
   14:   painting.country = current_user.country
   15:   painting.phone = current_user.phone
   16: end
```

If I understand, when I type "next", it should go to the line 14 but it go here : 

```
    47: def painting
 => 48:   @painting
    49: end
```

It is on the same file so it can be normal but, If I type "next" again I go to another file.

Is there something wrong?

Thanks!

**Comment by nixme** [comment] 2013-08-20 21:16
Are you on Ruby 2.0? This seems like a duplicate of #34 and a problem with debugger upstream.

**Comment by GCorbel** [comment] 2013-08-20 22:53
I updated ruby to the version 2.0.0-p247 nothing changed.

I used https://github.com/deivid-rodriguez/pry-byebug and it's worse. It stop at this line : https://github.com/deivid-rodriguez/pry-byebug/blob/master/lib/pry-byebug/processor.rb#L20. 

The only solution is to wait?

**Comment by nixme** [comment] 2013-08-21 01:03
All of Ruby 2.0, not any specific patchlevel, has this issue. @cldwalker is looking for patches if you're up for it – see https://github.com/cldwalker/debugger/issues/89

**Closed as completed** 2013-08-21 01:04 UTC

**Comment by deivid-rodriguez** [comment] 2013-08-21 01:34
Hi @GCorbel. If you want a solution for `pry-byebug` please submit a bug report there with instructions on how to reproduce the issue. I'll fix it if I can.

**Comment by GCorbel** [comment] 2013-08-21 15:34
Thanks, I found my issue. I was using pry-plus. In the gem, there this other gems included. There is probably an issue between pry-byebug and pry-exception_explorer or pry-rescue. It may be because there is the word "thrown" on the comments???

I'm not sure. I can probably investigate more deeper but I don't have the time right now.

Thanks for your help!

**Comment by deivid-rodriguez** [comment] 2013-08-28 02:16
Hi @GCorbel, I'm sorry I missed this message. I don't know what you mean by

> It may be because there is the word "thrown" on the comments???

Which comments? In any case, I don't think that would make any difference.

Salud!

**Comment by GCorbel** [comment] 2013-08-28 15:25
Yes, you're probably write. I was wrong. Now, I use only `pry-nav` `pry-byebug` et `pry-rails` and I have the same problem. I will submit an issue in pry-byebug.
