### ISSUE TITLE
next does not work (windows)

### ISSUE THREAD

**Issue by dhawal55** [nixme/pry-debugger#50] opened 2014-04-25 20:17 UTC
next command is supposed to step to the next line. However, I have had several instances where it just continues execution and does not stop at the next line. I'm running this on a windows box so this could be specific to windows.

**Comment by shoe** [comment] 2014-04-30 16:57
Possibly not specific to windows.  I see this behavior on Linux.

**Comment by markburns** [comment] 2014-05-05 04:54
same on OSX

**Comment by markburns** [comment] 2014-05-05 04:58
maybe a dupe of https://github.com/nixme/pry-debugger/issues/34 pry-byebug solves this issue for me

**Comment by nixme** [comment] 2014-07-02 19:32
Yes. Duplicate of #34. Please use `pry-byebug` in the meantime.

**Closed as completed by nixme** 2014-07-02 19:32 UTC
